name: Create Draft Release

on:
  push:
    branches:
      - fix-release-job

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Release v')

    steps:
      - name: Create draft release
        uses: actions/github-script@v7
        with:
         script: |
            const commits = github.event.commits || [];
            const versionPattern = /Release (v[0-9]+\.[0-9]+\.[0-9]+)/;
            let version = null;

            for (const commit of commits) {
              const match = commit.message.match(versionPattern);
              if (match) {
                version = match[1];
                break;
              }
            }

            if (!version) {
              throw new Error('No version found in any commit message');
            }

            const { data: release } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: version,
              generate_release_notes: true,
              draft: true,
            });

            console.log(`Draft release created: ${release.html_url}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
