name: Create Draft Release

on:
  push:
    branches:
      - fix-release-job

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Release v')

    steps:
      - name: Create draft release
        uses: actions/github-script@v7
        with:
         script: |
            const commitMessage = context.payload.head_commit.message;
            const versionPattern = /RELEASE (v[0-9]+\.[0-9]+\.[0-9]+)/;
            const match = commitMessage.match(versionPattern);

            if (!match) {
              throw new Error('No version found in commit message');
            }

            const version = match[1];

            const { data: release } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: version,
              generate_release_notes: true,
              draft: true,
            });

            console.log(`Draft release created: ${release.html_url}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
